language: node_js
sudo: required

node_js:
- "10"

cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq

install:
  - npm install

script:
  - ganache-cli -p 7545 --defaultBalanceEther 20000000000000000000 > /dev/null &
  - sleep 5
  - truffle migrate --network developmenttest
  - truffle test --network developmenttest